#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningEnglish.App_Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EnglishCenterDB")]
	public partial class EnglishCenterDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EnglishCenterDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EnglishCenterDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EnglishCenterDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnglishCenterDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnglishCenterDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnglishCenterDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<answer_tbl> answer_tbls
		{
			get
			{
				return this.GetTable<answer_tbl>();
			}
		}
		
		public System.Data.Linq.Table<examination_part_tbl> examination_part_tbls
		{
			get
			{
				return this.GetTable<examination_part_tbl>();
			}
		}
		
		public System.Data.Linq.Table<examination_question_tbl> examination_question_tbls
		{
			get
			{
				return this.GetTable<examination_question_tbl>();
			}
		}
		
		public System.Data.Linq.Table<examination_tbl> examination_tbls
		{
			get
			{
				return this.GetTable<examination_tbl>();
			}
		}
		
		public System.Data.Linq.Table<group_tbl> group_tbls
		{
			get
			{
				return this.GetTable<group_tbl>();
			}
		}
		
		public System.Data.Linq.Table<part_tbl> part_tbls
		{
			get
			{
				return this.GetTable<part_tbl>();
			}
		}
		
		public System.Data.Linq.Table<question_tbl> question_tbls
		{
			get
			{
				return this.GetTable<question_tbl>();
			}
		}
		
		public System.Data.Linq.Table<resource_link_tbl> resource_link_tbls
		{
			get
			{
				return this.GetTable<resource_link_tbl>();
			}
		}
		
		public System.Data.Linq.Table<resource_tbl> resource_tbls
		{
			get
			{
				return this.GetTable<resource_tbl>();
			}
		}
		
		public System.Data.Linq.Table<role_detail_tbl> role_detail_tbls
		{
			get
			{
				return this.GetTable<role_detail_tbl>();
			}
		}
		
		public System.Data.Linq.Table<role_tbl> role_tbls
		{
			get
			{
				return this.GetTable<role_tbl>();
			}
		}
		
		public System.Data.Linq.Table<staff_tbl> staff_tbls
		{
			get
			{
				return this.GetTable<staff_tbl>();
			}
		}
		
		public System.Data.Linq.Table<topic_tbl> topic_tbls
		{
			get
			{
				return this.GetTable<topic_tbl>();
			}
		}
		
		public System.Data.Linq.Table<user_answer_question_detail_tbl> user_answer_question_detail_tbls
		{
			get
			{
				return this.GetTable<user_answer_question_detail_tbl>();
			}
		}
		
		public System.Data.Linq.Table<user_answer_question_tbl> user_answer_question_tbls
		{
			get
			{
				return this.GetTable<user_answer_question_tbl>();
			}
		}
		
		public System.Data.Linq.Table<user_tbl> user_tbls
		{
			get
			{
				return this.GetTable<user_tbl>();
			}
		}
		
		public System.Data.Linq.Table<examination_topic_tbl> examination_topic_tbls
		{
			get
			{
				return this.GetTable<examination_topic_tbl>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.answer_tbl")]
	public partial class answer_tbl
	{
		
		private System.Nullable<int> _id;
		
		private string _answer_id;
		
		private string _question_id;
		
		private string _answer_content;
		
		private string _answer_title;
		
		private string _resource_id;
		
		private System.Nullable<int> _examination_order;
		
		private string _notes;
		
		private System.Nullable<bool> _delete_flag;
		
		public answer_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_id", DbType="NChar(50)")]
		public string answer_id
		{
			get
			{
				return this._answer_id;
			}
			set
			{
				if ((this._answer_id != value))
				{
					this._answer_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", DbType="NChar(50)")]
		public string question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this._question_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_content", DbType="NVarChar(MAX)")]
		public string answer_content
		{
			get
			{
				return this._answer_content;
			}
			set
			{
				if ((this._answer_content != value))
				{
					this._answer_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_title", DbType="NVarChar(50)")]
		public string answer_title
		{
			get
			{
				return this._answer_title;
			}
			set
			{
				if ((this._answer_title != value))
				{
					this._answer_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resource_id", DbType="NChar(50)")]
		public string resource_id
		{
			get
			{
				return this._resource_id;
			}
			set
			{
				if ((this._resource_id != value))
				{
					this._resource_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_order", DbType="Int")]
		public System.Nullable<int> examination_order
		{
			get
			{
				return this._examination_order;
			}
			set
			{
				if ((this._examination_order != value))
				{
					this._examination_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit")]
		public System.Nullable<bool> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this._delete_flag = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.examination_part_tbl")]
	public partial class examination_part_tbl
	{
		
		private string _examination_id;
		
		private System.Nullable<int> _examination_order;
		
		private string _part_id;
		
		private System.Nullable<int> _part_order;
		
		private string _part_content;
		
		private string _part_title;
		
		public examination_part_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_id", DbType="NChar(50)")]
		public string examination_id
		{
			get
			{
				return this._examination_id;
			}
			set
			{
				if ((this._examination_id != value))
				{
					this._examination_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_order", DbType="Int")]
		public System.Nullable<int> examination_order
		{
			get
			{
				return this._examination_order;
			}
			set
			{
				if ((this._examination_order != value))
				{
					this._examination_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_id", DbType="NChar(50)")]
		public string part_id
		{
			get
			{
				return this._part_id;
			}
			set
			{
				if ((this._part_id != value))
				{
					this._part_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_order", DbType="Int")]
		public System.Nullable<int> part_order
		{
			get
			{
				return this._part_order;
			}
			set
			{
				if ((this._part_order != value))
				{
					this._part_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_content", DbType="NVarChar(MAX)")]
		public string part_content
		{
			get
			{
				return this._part_content;
			}
			set
			{
				if ((this._part_content != value))
				{
					this._part_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_title", DbType="NVarChar(MAX)")]
		public string part_title
		{
			get
			{
				return this._part_title;
			}
			set
			{
				if ((this._part_title != value))
				{
					this._part_title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.examination_question_tbl")]
	public partial class examination_question_tbl
	{
		
		private string _examination_id;
		
		private string _question_id;
		
		private string _question_code;
		
		private System.Nullable<int> _examination_order;
		
		public examination_question_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_id", DbType="NChar(50)")]
		public string examination_id
		{
			get
			{
				return this._examination_id;
			}
			set
			{
				if ((this._examination_id != value))
				{
					this._examination_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", DbType="NChar(50)")]
		public string question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this._question_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_code", DbType="NChar(10)")]
		public string question_code
		{
			get
			{
				return this._question_code;
			}
			set
			{
				if ((this._question_code != value))
				{
					this._question_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_order", DbType="Int")]
		public System.Nullable<int> examination_order
		{
			get
			{
				return this._examination_order;
			}
			set
			{
				if ((this._examination_order != value))
				{
					this._examination_order = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.examination_tbl")]
	public partial class examination_tbl
	{
		
		private string _id;
		
		private string _name;
		
		private System.Nullable<int> _num_question;
		
		private string _type;
		
		private string _course;
		
		private System.Nullable<int> _course_level;
		
		private System.Nullable<int> _num_part;
		
		public examination_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(50)")]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_question", DbType="Int")]
		public System.Nullable<int> num_question
		{
			get
			{
				return this._num_question;
			}
			set
			{
				if ((this._num_question != value))
				{
					this._num_question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NChar(10)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course", DbType="NVarChar(MAX)")]
		public string course
		{
			get
			{
				return this._course;
			}
			set
			{
				if ((this._course != value))
				{
					this._course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_level", DbType="Int")]
		public System.Nullable<int> course_level
		{
			get
			{
				return this._course_level;
			}
			set
			{
				if ((this._course_level != value))
				{
					this._course_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_part", DbType="Int")]
		public System.Nullable<int> num_part
		{
			get
			{
				return this._num_part;
			}
			set
			{
				if ((this._num_part != value))
				{
					this._num_part = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.group_tbl")]
	public partial class group_tbl
	{
		
		private int _id;
		
		private string _group_code;
		
		private string _group_name;
		
		public group_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_code", DbType="NChar(10)")]
		public string group_code
		{
			get
			{
				return this._group_code;
			}
			set
			{
				if ((this._group_code != value))
				{
					this._group_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_name", DbType="NVarChar(50)")]
		public string group_name
		{
			get
			{
				return this._group_name;
			}
			set
			{
				if ((this._group_name != value))
				{
					this._group_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.part_tbl")]
	public partial class part_tbl
	{
		
		private string _part_id;
		
		private string _part_title;
		
		private string _part_content;
		
		private string _part_type;
		
		private string _part_resource;
		
		private System.Nullable<bool> _delete_flag;
		
		public part_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_id", DbType="NChar(50)")]
		public string part_id
		{
			get
			{
				return this._part_id;
			}
			set
			{
				if ((this._part_id != value))
				{
					this._part_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_title", DbType="NVarChar(MAX)")]
		public string part_title
		{
			get
			{
				return this._part_title;
			}
			set
			{
				if ((this._part_title != value))
				{
					this._part_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_content", DbType="NVarChar(MAX)")]
		public string part_content
		{
			get
			{
				return this._part_content;
			}
			set
			{
				if ((this._part_content != value))
				{
					this._part_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_type", DbType="NVarChar(50)")]
		public string part_type
		{
			get
			{
				return this._part_type;
			}
			set
			{
				if ((this._part_type != value))
				{
					this._part_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_resource", DbType="NVarChar(MAX)")]
		public string part_resource
		{
			get
			{
				return this._part_resource;
			}
			set
			{
				if ((this._part_resource != value))
				{
					this._part_resource = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit")]
		public System.Nullable<bool> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this._delete_flag = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.question_tbl")]
	public partial class question_tbl
	{
		
		private int _id;
		
		private System.Nullable<int> _examination_order;
		
		private string _examination_id;
		
		private string _question_id;
		
		private string _question_name;
		
		private string _question_content;
		
		private string _examination_part_id;
		
		private System.Nullable<int> _question_order;
		
		private string _question_type;
		
		private System.Nullable<int> _num_correct_answer;
		
		private System.Nullable<int> _total_num_answer;
		
		private string _resource_id;
		
		private string _notes;
		
		private string _question_code;
		
		public question_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_order", DbType="Int")]
		public System.Nullable<int> examination_order
		{
			get
			{
				return this._examination_order;
			}
			set
			{
				if ((this._examination_order != value))
				{
					this._examination_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_id", DbType="NChar(50)")]
		public string examination_id
		{
			get
			{
				return this._examination_id;
			}
			set
			{
				if ((this._examination_id != value))
				{
					this._examination_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", DbType="NChar(50)")]
		public string question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this._question_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_name", DbType="NVarChar(50)")]
		public string question_name
		{
			get
			{
				return this._question_name;
			}
			set
			{
				if ((this._question_name != value))
				{
					this._question_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_content", DbType="NVarChar(MAX)")]
		public string question_content
		{
			get
			{
				return this._question_content;
			}
			set
			{
				if ((this._question_content != value))
				{
					this._question_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_part_id", DbType="NChar(50)")]
		public string examination_part_id
		{
			get
			{
				return this._examination_part_id;
			}
			set
			{
				if ((this._examination_part_id != value))
				{
					this._examination_part_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_order", DbType="Int")]
		public System.Nullable<int> question_order
		{
			get
			{
				return this._question_order;
			}
			set
			{
				if ((this._question_order != value))
				{
					this._question_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_type", DbType="NChar(50)")]
		public string question_type
		{
			get
			{
				return this._question_type;
			}
			set
			{
				if ((this._question_type != value))
				{
					this._question_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_correct_answer", DbType="Int")]
		public System.Nullable<int> num_correct_answer
		{
			get
			{
				return this._num_correct_answer;
			}
			set
			{
				if ((this._num_correct_answer != value))
				{
					this._num_correct_answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_num_answer", DbType="Int")]
		public System.Nullable<int> total_num_answer
		{
			get
			{
				return this._total_num_answer;
			}
			set
			{
				if ((this._total_num_answer != value))
				{
					this._total_num_answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resource_id", DbType="NChar(50)")]
		public string resource_id
		{
			get
			{
				return this._resource_id;
			}
			set
			{
				if ((this._resource_id != value))
				{
					this._resource_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_code", DbType="NChar(10)")]
		public string question_code
		{
			get
			{
				return this._question_code;
			}
			set
			{
				if ((this._question_code != value))
				{
					this._question_code = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.resource_link_tbl")]
	public partial class resource_link_tbl
	{
		
		private string _resource_id;
		
		private System.Nullable<bool> _active;
		
		private string _url;
		
		private System.Nullable<byte> _location_type;
		
		private string _url_host_name;
		
		private string _resource_type;
		
		private System.Nullable<bool> _delete_flag;
		
		public resource_link_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resource_id", DbType="NChar(50)")]
		public string resource_id
		{
			get
			{
				return this._resource_id;
			}
			set
			{
				if ((this._resource_id != value))
				{
					this._resource_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(250)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this._url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_type", DbType="TinyInt")]
		public System.Nullable<byte> location_type
		{
			get
			{
				return this._location_type;
			}
			set
			{
				if ((this._location_type != value))
				{
					this._location_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url_host_name", DbType="NVarChar(150)")]
		public string url_host_name
		{
			get
			{
				return this._url_host_name;
			}
			set
			{
				if ((this._url_host_name != value))
				{
					this._url_host_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resource_type", DbType="NChar(10)")]
		public string resource_type
		{
			get
			{
				return this._resource_type;
			}
			set
			{
				if ((this._resource_type != value))
				{
					this._resource_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit")]
		public System.Nullable<bool> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this._delete_flag = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.resource_tbl")]
	public partial class resource_tbl
	{
		
		private string _resource_id;
		
		private string _name;
		
		private string _type;
		
		private System.Nullable<byte> _location_type;
		
		private System.Nullable<int> _examination_order;
		
		private System.Nullable<bool> _delete_flag;
		
		public resource_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resource_id", DbType="NChar(50)")]
		public string resource_id
		{
			get
			{
				return this._resource_id;
			}
			set
			{
				if ((this._resource_id != value))
				{
					this._resource_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NChar(10)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_type", DbType="TinyInt")]
		public System.Nullable<byte> location_type
		{
			get
			{
				return this._location_type;
			}
			set
			{
				if ((this._location_type != value))
				{
					this._location_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_order", DbType="Int")]
		public System.Nullable<int> examination_order
		{
			get
			{
				return this._examination_order;
			}
			set
			{
				if ((this._examination_order != value))
				{
					this._examination_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit")]
		public System.Nullable<bool> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this._delete_flag = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.role_detail_tbl")]
	public partial class role_detail_tbl
	{
		
		private System.Nullable<int> _role_code;
		
		private System.Nullable<int> _function_id;
		
		private string _function_name;
		
		public role_detail_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_code", DbType="Int")]
		public System.Nullable<int> role_code
		{
			get
			{
				return this._role_code;
			}
			set
			{
				if ((this._role_code != value))
				{
					this._role_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_function_id", DbType="Int")]
		public System.Nullable<int> function_id
		{
			get
			{
				return this._function_id;
			}
			set
			{
				if ((this._function_id != value))
				{
					this._function_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_function_name", DbType="NVarChar(50)")]
		public string function_name
		{
			get
			{
				return this._function_name;
			}
			set
			{
				if ((this._function_name != value))
				{
					this._function_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.role_tbl")]
	public partial class role_tbl
	{
		
		private System.Nullable<int> _role_code;
		
		private string _role_name;
		
		public role_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_code", DbType="Int")]
		public System.Nullable<int> role_code
		{
			get
			{
				return this._role_code;
			}
			set
			{
				if ((this._role_code != value))
				{
					this._role_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_name", DbType="NVarChar(50)")]
		public string role_name
		{
			get
			{
				return this._role_name;
			}
			set
			{
				if ((this._role_name != value))
				{
					this._role_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.staff_tbl")]
	public partial class staff_tbl
	{
		
		private int _id;
		
		private string _staff_code;
		
		private System.Nullable<bool> _is_admin;
		
		private string _group_code;
		
		private string _first_name;
		
		private string _last_name;
		
		private string _fullname;
		
		private string _nick_name;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _gender;
		
		private string _country_name;
		
		private string _country_code;
		
		private System.Nullable<byte> _marital_status;
		
		private string _address1;
		
		private string _address2;
		
		private string _tel1;
		
		private string _tel2;
		
		private string _email1;
		
		private string _email2;
		
		private string _manager_code;
		
		private System.Nullable<System.DateTime> _join_date;
		
		private string _avatar_path;
		
		private string _status;
		
		private string _account_status;
		
		private string _user_name;
		
		private string _password;
		
		private System.Nullable<System.DateTime> _update_date;
		
		private System.Nullable<bool> _delete_flag;
		
		public staff_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_code", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string staff_code
		{
			get
			{
				return this._staff_code;
			}
			set
			{
				if ((this._staff_code != value))
				{
					this._staff_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_admin", DbType="Bit")]
		public System.Nullable<bool> is_admin
		{
			get
			{
				return this._is_admin;
			}
			set
			{
				if ((this._is_admin != value))
				{
					this._is_admin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_code", DbType="NChar(10)")]
		public string group_code
		{
			get
			{
				return this._group_code;
			}
			set
			{
				if ((this._group_code != value))
				{
					this._group_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NVarChar(50)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this._first_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(50)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this._last_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(50)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this._fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nick_name", DbType="NVarChar(50)")]
		public string nick_name
		{
			get
			{
				return this._nick_name;
			}
			set
			{
				if ((this._nick_name != value))
				{
					this._nick_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NChar(10)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_name", DbType="NVarChar(50)")]
		public string country_name
		{
			get
			{
				return this._country_name;
			}
			set
			{
				if ((this._country_name != value))
				{
					this._country_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_code", DbType="NChar(3)")]
		public string country_code
		{
			get
			{
				return this._country_code;
			}
			set
			{
				if ((this._country_code != value))
				{
					this._country_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marital_status", DbType="TinyInt")]
		public System.Nullable<byte> marital_status
		{
			get
			{
				return this._marital_status;
			}
			set
			{
				if ((this._marital_status != value))
				{
					this._marital_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address1", DbType="NVarChar(500)")]
		public string address1
		{
			get
			{
				return this._address1;
			}
			set
			{
				if ((this._address1 != value))
				{
					this._address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address2", DbType="NVarChar(500)")]
		public string address2
		{
			get
			{
				return this._address2;
			}
			set
			{
				if ((this._address2 != value))
				{
					this._address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1", DbType="NChar(20)")]
		public string tel1
		{
			get
			{
				return this._tel1;
			}
			set
			{
				if ((this._tel1 != value))
				{
					this._tel1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2", DbType="NChar(20)")]
		public string tel2
		{
			get
			{
				return this._tel2;
			}
			set
			{
				if ((this._tel2 != value))
				{
					this._tel2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email1", DbType="NChar(50)")]
		public string email1
		{
			get
			{
				return this._email1;
			}
			set
			{
				if ((this._email1 != value))
				{
					this._email1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email2", DbType="NChar(50)")]
		public string email2
		{
			get
			{
				return this._email2;
			}
			set
			{
				if ((this._email2 != value))
				{
					this._email2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manager_code", DbType="NChar(20)")]
		public string manager_code
		{
			get
			{
				return this._manager_code;
			}
			set
			{
				if ((this._manager_code != value))
				{
					this._manager_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_join_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> join_date
		{
			get
			{
				return this._join_date;
			}
			set
			{
				if ((this._join_date != value))
				{
					this._join_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar_path", DbType="NVarChar(500)")]
		public string avatar_path
		{
			get
			{
				return this._avatar_path;
			}
			set
			{
				if ((this._avatar_path != value))
				{
					this._avatar_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_status", DbType="NChar(10)")]
		public string account_status
		{
			get
			{
				return this._account_status;
			}
			set
			{
				if ((this._account_status != value))
				{
					this._account_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(20)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this._update_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit")]
		public System.Nullable<bool> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this._delete_flag = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.topic_tbl")]
	public partial class topic_tbl
	{
		
		private string _topic_id;
		
		private string _topic_type;
		
		private string _topic_title;
		
		private string _topic_content;
		
		private string _topic_resource;
		
		private System.Nullable<bool> _delete_flag;
		
		public topic_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_id", DbType="NChar(50)")]
		public string topic_id
		{
			get
			{
				return this._topic_id;
			}
			set
			{
				if ((this._topic_id != value))
				{
					this._topic_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_type", DbType="NChar(50)")]
		public string topic_type
		{
			get
			{
				return this._topic_type;
			}
			set
			{
				if ((this._topic_type != value))
				{
					this._topic_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_title", DbType="NVarChar(MAX)")]
		public string topic_title
		{
			get
			{
				return this._topic_title;
			}
			set
			{
				if ((this._topic_title != value))
				{
					this._topic_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_content", DbType="NVarChar(MAX)")]
		public string topic_content
		{
			get
			{
				return this._topic_content;
			}
			set
			{
				if ((this._topic_content != value))
				{
					this._topic_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_resource", DbType="NVarChar(MAX)")]
		public string topic_resource
		{
			get
			{
				return this._topic_resource;
			}
			set
			{
				if ((this._topic_resource != value))
				{
					this._topic_resource = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit")]
		public System.Nullable<bool> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this._delete_flag = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_answer_question_detail_tbl")]
	public partial class user_answer_question_detail_tbl
	{
		
		private string _customer_question_id;
		
		private string _answer_id;
		
		public user_answer_question_detail_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_question_id", DbType="NChar(50)")]
		public string customer_question_id
		{
			get
			{
				return this._customer_question_id;
			}
			set
			{
				if ((this._customer_question_id != value))
				{
					this._customer_question_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_id", DbType="NChar(50)")]
		public string answer_id
		{
			get
			{
				return this._answer_id;
			}
			set
			{
				if ((this._answer_id != value))
				{
					this._answer_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_answer_question_tbl")]
	public partial class user_answer_question_tbl
	{
		
		private int _id;
		
		private string _question_id;
		
		private string _user_id;
		
		private string _user_question_id;
		
		public user_answer_question_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", DbType="NChar(50)")]
		public string question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this._question_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="NChar(20)")]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_question_id", DbType="NChar(50)")]
		public string user_question_id
		{
			get
			{
				return this._user_question_id;
			}
			set
			{
				if ((this._user_question_id != value))
				{
					this._user_question_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_tbl")]
	public partial class user_tbl
	{
		
		private int _id;
		
		private string _user_code;
		
		private string _user_type;
		
		private string _first_name;
		
		private string _last_name;
		
		private string _full_name;
		
		private string _nick_name;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _gender;
		
		private string _country_name;
		
		private string _country_code;
		
		private System.Nullable<byte> _marital_status;
		
		private string _address1;
		
		private string _address2;
		
		private string _tel1;
		
		private string _tel2;
		
		private string _email1;
		
		private string _email2;
		
		private string _referral_code;
		
		private string _instructor_code;
		
		private System.Nullable<System.DateTime> _join_date;
		
		private string _avatar_path;
		
		private string _status;
		
		private string _account_status;
		
		private string _user_name;
		
		private string _password;
		
		private System.Nullable<System.DateTime> _update_date;
		
		private bool _delete_flag;
		
		private bool _active;
		
		private string _role_code;
		
		public user_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_code", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string user_code
		{
			get
			{
				return this._user_code;
			}
			set
			{
				if ((this._user_code != value))
				{
					this._user_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type", DbType="NChar(10)")]
		public string user_type
		{
			get
			{
				return this._user_type;
			}
			set
			{
				if ((this._user_type != value))
				{
					this._user_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this._first_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(50)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this._last_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="NVarChar(50)")]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this._full_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nick_name", DbType="NVarChar(50)")]
		public string nick_name
		{
			get
			{
				return this._nick_name;
			}
			set
			{
				if ((this._nick_name != value))
				{
					this._nick_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NChar(10)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_name", DbType="NVarChar(50)")]
		public string country_name
		{
			get
			{
				return this._country_name;
			}
			set
			{
				if ((this._country_name != value))
				{
					this._country_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_code", DbType="NChar(3)")]
		public string country_code
		{
			get
			{
				return this._country_code;
			}
			set
			{
				if ((this._country_code != value))
				{
					this._country_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marital_status", DbType="TinyInt")]
		public System.Nullable<byte> marital_status
		{
			get
			{
				return this._marital_status;
			}
			set
			{
				if ((this._marital_status != value))
				{
					this._marital_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address1", DbType="NVarChar(500)")]
		public string address1
		{
			get
			{
				return this._address1;
			}
			set
			{
				if ((this._address1 != value))
				{
					this._address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address2", DbType="NVarChar(500)")]
		public string address2
		{
			get
			{
				return this._address2;
			}
			set
			{
				if ((this._address2 != value))
				{
					this._address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1", DbType="NChar(20)")]
		public string tel1
		{
			get
			{
				return this._tel1;
			}
			set
			{
				if ((this._tel1 != value))
				{
					this._tel1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2", DbType="NChar(20)")]
		public string tel2
		{
			get
			{
				return this._tel2;
			}
			set
			{
				if ((this._tel2 != value))
				{
					this._tel2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email1", DbType="NChar(50)")]
		public string email1
		{
			get
			{
				return this._email1;
			}
			set
			{
				if ((this._email1 != value))
				{
					this._email1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email2", DbType="NChar(50)")]
		public string email2
		{
			get
			{
				return this._email2;
			}
			set
			{
				if ((this._email2 != value))
				{
					this._email2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referral_code", DbType="NChar(20)")]
		public string referral_code
		{
			get
			{
				return this._referral_code;
			}
			set
			{
				if ((this._referral_code != value))
				{
					this._referral_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instructor_code", DbType="NChar(20)")]
		public string instructor_code
		{
			get
			{
				return this._instructor_code;
			}
			set
			{
				if ((this._instructor_code != value))
				{
					this._instructor_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_join_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> join_date
		{
			get
			{
				return this._join_date;
			}
			set
			{
				if ((this._join_date != value))
				{
					this._join_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar_path", DbType="NVarChar(500)")]
		public string avatar_path
		{
			get
			{
				return this._avatar_path;
			}
			set
			{
				if ((this._avatar_path != value))
				{
					this._avatar_path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_status", DbType="NChar(10)")]
		public string account_status
		{
			get
			{
				return this._account_status;
			}
			set
			{
				if ((this._account_status != value))
				{
					this._account_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NChar(50)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this._user_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(20)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this._update_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit NOT NULL")]
		public bool delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this._delete_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_code", DbType="NChar(10)")]
		public string role_code
		{
			get
			{
				return this._role_code;
			}
			set
			{
				if ((this._role_code != value))
				{
					this._role_code = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.examination_topic_tbl")]
	public partial class examination_topic_tbl
	{
		
		private string _topic_id;
		
		private System.Nullable<int> _examination_order;
		
		private System.Nullable<int> _topic_type;
		
		private string _topic_title;
		
		private string _topic_content;
		
		private string _topic_resource_id;
		
		private System.Nullable<int> _topic_order;
		
		private string _part_id;
		
		private string _examination_id;
		
		private System.Nullable<bool> _delete_flag;
		
		public examination_topic_tbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_id", DbType="NChar(50)")]
		public string topic_id
		{
			get
			{
				return this._topic_id;
			}
			set
			{
				if ((this._topic_id != value))
				{
					this._topic_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_order", DbType="Int")]
		public System.Nullable<int> examination_order
		{
			get
			{
				return this._examination_order;
			}
			set
			{
				if ((this._examination_order != value))
				{
					this._examination_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_type", DbType="Int")]
		public System.Nullable<int> topic_type
		{
			get
			{
				return this._topic_type;
			}
			set
			{
				if ((this._topic_type != value))
				{
					this._topic_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_title", DbType="NVarChar(MAX)")]
		public string topic_title
		{
			get
			{
				return this._topic_title;
			}
			set
			{
				if ((this._topic_title != value))
				{
					this._topic_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_content", DbType="NVarChar(MAX)")]
		public string topic_content
		{
			get
			{
				return this._topic_content;
			}
			set
			{
				if ((this._topic_content != value))
				{
					this._topic_content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_resource_id", DbType="NChar(50)")]
		public string topic_resource_id
		{
			get
			{
				return this._topic_resource_id;
			}
			set
			{
				if ((this._topic_resource_id != value))
				{
					this._topic_resource_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic_order", DbType="Int")]
		public System.Nullable<int> topic_order
		{
			get
			{
				return this._topic_order;
			}
			set
			{
				if ((this._topic_order != value))
				{
					this._topic_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_id", DbType="NChar(50)")]
		public string part_id
		{
			get
			{
				return this._part_id;
			}
			set
			{
				if ((this._part_id != value))
				{
					this._part_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_examination_id", DbType="NChar(10)")]
		public string examination_id
		{
			get
			{
				return this._examination_id;
			}
			set
			{
				if ((this._examination_id != value))
				{
					this._examination_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Bit")]
		public System.Nullable<bool> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this._delete_flag = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
